baseURL: 'https://bverbeken.github.io'
languageCode: 'en-us'
title: '"Just"'
theme: "anubis"
enableRobotsTXT: true

languages:
  en:
    languageName: English
    weight: 1
    contentDir: content/en
    menu:
      main:
        - name: Archive
          url: /posts/
          weight: 1
        - name: About
          url: /about/
          weight: 2

  nl:
    languageName: Nederlands
    weight: 2
    contentDir: content/nl
    menu:
      main:
        - name: Archief
          url: /posts/
          weight: 1
        - name: Over
          url: /about/
          weight: 2

params:
  author: Ben Verbeken
  email: bverbeken@gmail.com
  style: dark-without-switcher
  dateFormat: 2 January 2006
  readMore: false
  disableSummary: false
  customCSS:
    - css/colors.css
    - css/my.css # relative path to "assets" directory (don't use main.css filename)
  social:
    - id: github
      url: https://github.com/bverbeken
    - id: strava
      url: https://www.strava.com/athletes/63708615
    - id: goodreads
      url: https://www.goodreads.com/user/show/6076790-ben

menu:
  main:
    - identifier: archive
      name: Archive
      title: Archive
      url: /posts/
      weight: 1
    - identifier: about
      name: About
      title: About
      url: /about/
      weight: 2


sitemap:
  changefreq: "monthly"
  priority: 0.5
  filename: "sitemap.xml"

