baseURL: 'https://bverbeken.github.io'
languageCode: 'en-us'
title: '"Just"'
theme: "anubis"
enableRobotsTXT: true

params:
  author: Ben Verbeken
  email: bverbeken@gmail.com
  style: dark-without-switcher
  dateFormat: 2 January 2006
  readMore: false
  disableSummary: false
  customCSS:
    - css/colors.css
    - css/my.css # relative path to "assets" directory (don't use main.css filename)
  social:
    - id: github
      url: https://github.com/bverbeken
    - id: strava
      url: https://www.strava.com/athletes/63708615
    - id: goodreads
      url: https://www.goodreads.com/user/show/6076790-ben

taxonomies:
    language: lang

contentDir: content
menu:
  main:
    - name: English
      weight: 1
      url: /tags/en/
    - name: Dutch
      weight: 2
      url: /tags/nl/
    - name: Archive
      weight: 3
      url: /posts/
    - name: About
      weight: 4
      url: /about/

sitemap:
  changefreq: "monthly"
  priority: 0.5
  filename: "sitemap.xml"

