baseURL: 'https://bverbeken.github.io'
languageCode: 'en-us'
title: '"Just"'
theme: "ananke"
params:
  author: "Ben Verbeken"
  ananke_socials:
    - name: github
      url: https://github.com/bverbeken
    - name: strava
      url: https://www.strava.com/athletes/63708615
      label: strava
      color: '#FC5201'
    - name: goodreads
      url: https://www.goodreads.com/user/show/6076790-ben
      label: goodreads
      color: '#B9AC9A'
  background_color_class: "bg-dark-gray"
  recent_posts_number: 5

menu:
  main:
    - identifier: blog
      name: Blog
      title: Blog
      url: /posts/
      weight: 1
    - identifier: about
      name: About
      title: About
      url: /about/
      weight: 2


sitemap:
  changefreq: "monthly"
  priority: 0.5
  filename: "sitemap.xml"

